packages:
  - 'factory'
  - 'athena-api'
  - 'factory/athena-dashboard-ui'
  - 'sites/*'
  - '../control/sitetypes-preview/*'

onlyBuiltDependencies:
  - esbuild
  - lightningcss
  - core-js
  - canvas
